using Infrastructure.Security.Models;

namespace Tests.Infrastructure.Security.Configurations;

[Trait("Category", "Integration")]
[Collection(nameof(DatabaseCollection))]
public class RateLimitEntryConfigurationTests(PostgresContainerFixture fixture) : IAsyncLifetime
{
    private readonly PostgresContainerFixture _fixture = fixture;

    public Task InitializeAsync() => Task.CompletedTask;

    public async Task DisposeAsync()
    {
        await _fixture.ResetAsync();
    }

    [Fact]
    public void Model_KeyProperty_IsRequiredAndHasMaxLength300()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        using var context = _fixture.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(RateLimitEntry));
        entityType.ShouldNotBeNull();

        var keyProperty = entityType!.FindProperty(nameof(RateLimitEntry.Key));
        keyProperty.ShouldNotBeNull();
        keyProperty!.GetMaxLength().ShouldBe(300);
        keyProperty.IsNullable.ShouldBeFalse();
    }

    [Fact]
    public void Model_WindowKeyProperty_IsRequiredAndHasMaxLength100()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        using var context = _fixture.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(RateLimitEntry));
        entityType.ShouldNotBeNull();

        var windowKeyProperty = entityType!.FindProperty(nameof(RateLimitEntry.WindowKey));
        windowKeyProperty.ShouldNotBeNull();
        windowKeyProperty!.GetMaxLength().ShouldBe(100);
        windowKeyProperty.IsNullable.ShouldBeFalse();
    }

    [Fact]
    public void Model_PrimaryKey_IsIdProperty()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        using var context = _fixture.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(RateLimitEntry));
        entityType.ShouldNotBeNull();

        var primaryKey = entityType!.FindPrimaryKey();
        primaryKey.ShouldNotBeNull();
        primaryKey!.Properties.Count.ShouldBe(1);
        primaryKey.Properties[0].Name.ShouldBe(nameof(RateLimitEntry.Id));
    }

    [Fact]
    public void Model_HasUniqueCompositeIndexOnKeyAndWindowKey()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        using var context = _fixture.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(RateLimitEntry));
        entityType.ShouldNotBeNull();

        var compositeIndex = entityType!.GetIndexes().SingleOrDefault(i =>
            i.Properties.Count == 2
            && i.Properties.Any(p => p.Name == nameof(RateLimitEntry.Key))
            && i.Properties.Any(p => p.Name == nameof(RateLimitEntry.WindowKey)));

        compositeIndex.ShouldNotBeNull();
        compositeIndex!.IsUnique.ShouldBeTrue();
    }

    [Fact]
    public async Task SaveChangesAsync_WhenPersistingSingleEntry_AssignsAutoGeneratedId()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        await using var context = _fixture.CreateContext();

        var entry = new RateLimitEntry
        {
            Key = "unit:persist:key",
            WindowKey = "unit:persist:window",
            Count = 1,
            ExpiresAt = DateTime.UtcNow.AddMinutes(15)
        };

        context.RateLimitEntries.Add(entry);
        await context.SaveChangesAsync();

        entry.Id.ShouldBeGreaterThan(0);

        var reloaded = await context.RateLimitEntries.SingleAsync(e => e.Id == entry.Id);
        reloaded.Key.ShouldBe("unit:persist:key");
        reloaded.WindowKey.ShouldBe("unit:persist:window");
        reloaded.Count.ShouldBe(1);
    }

    [Fact]
    public async Task SaveChangesAsync_WhenInsertingDuplicateKeyAndWindowKey_ThrowsDbUpdateException()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        await using var seedContext = _fixture.CreateContext();
        seedContext.RateLimitEntries.Add(new RateLimitEntry
        {
            Key = "unit:dup:key",
            WindowKey = "unit:dup:window",
            Count = 1,
            ExpiresAt = DateTime.UtcNow.AddMinutes(15)
        });
        await seedContext.SaveChangesAsync();

        await using var duplicateContext = _fixture.CreateContext();
        duplicateContext.RateLimitEntries.Add(new RateLimitEntry
        {
            Key = "unit:dup:key",
            WindowKey = "unit:dup:window",
            Count = 2,
            ExpiresAt = DateTime.UtcNow.AddMinutes(30)
        });

        Func<Task> act = async () => await duplicateContext.SaveChangesAsync();

        await act.ShouldThrowAsync<DbUpdateException>();
    }

    [Fact]
    public async Task SaveChangesAsync_WhenKeysDifferOnlyByWindowKey_AllowsBothRecords()
    {
        Skip.IfNot(_fixture.IsDockerAvailable, _fixture.UnavailabilityReason ?? "Docker engine not available.");

        await using var context = _fixture.CreateContext();

        context.RateLimitEntries.Add(new RateLimitEntry
        {
            Key = "unit:same-key",
            WindowKey = "window-a",
            Count = 1,
            ExpiresAt = DateTime.UtcNow.AddMinutes(15)
        });
        context.RateLimitEntries.Add(new RateLimitEntry
        {
            Key = "unit:same-key",
            WindowKey = "window-b",
            Count = 1,
            ExpiresAt = DateTime.UtcNow.AddMinutes(15)
        });

        await context.SaveChangesAsync();

        var count = await context.RateLimitEntries.CountAsync(e => e.Key == "unit:same-key");
        count.ShouldBe(2);
    }
}
