global using Application.Common.Interfaces;
global using Application.Common.Interfaces.Persistence;
global using Application.Common.Models;
global using Application.DTOs;
global using AutoMapper;
global using Ganss.Xss;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.ComponentModel.DataAnnotations;
global using System.Security.Cryptography;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using BCryptNet = BCrypt.Net.BCrypt;
