CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AttributeTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_AttributeTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "EventType" character varying(50) NOT NULL,
    "Action" character varying(100) NOT NULL,
    "Details" text NOT NULL,
    "IpAddress" character varying(45) NOT NULL,
    "UserAgent" character varying(500),
    "Timestamp" timestamp with time zone NOT NULL,
    "IntegrityHash" character varying(100) NOT NULL,
    "IsArchived" boolean NOT NULL DEFAULT FALSE,
    "ArchivedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Description" text,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "DiscountCodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Percentage" numeric(5,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_DiscountCodes" PRIMARY KEY ("Id")
);

CREATE TABLE "ElasticsearchOutboxMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" character varying(100),
    "EntityId" character varying(100),
    "OperationType" character varying(50),
    "Payload" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsProcessed" boolean NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "Document" text,
    "ChangeType" character varying(50),
    "RetryCount" integer NOT NULL,
    "Error" text,
    CONSTRAINT "PK_ElasticsearchOutboxMessages" PRIMARY KEY ("Id")
);

CREATE TABLE "FailedElasticOperations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" character varying(100) NOT NULL,
    "Document" text NOT NULL,
    "Error" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "RetryCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "LastRetryAt" timestamp with time zone,
    CONSTRAINT "PK_FailedElasticOperations" PRIMARY KEY ("Id")
);

CREATE TABLE "OrderStatus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Icon" character varying(100),
    "Color" character varying(50),
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDefault" boolean NOT NULL,
    "AllowCancel" boolean NOT NULL,
    "AllowEdit" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_OrderStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "OutboxMessages" (
    "Id" uuid NOT NULL,
    "Type" character varying(500) NOT NULL,
    "Payload" text NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "Error" character varying(2000),
    CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
);

CREATE TABLE "RateLimits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(256) NOT NULL,
    "Count" integer NOT NULL,
    "LastAttempt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_RateLimits" PRIMARY KEY ("Id")
);

CREATE TABLE "Shippings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "BaseCost" numeric(18,2) NOT NULL,
    "EstimatedDeliveryTime" character varying(100),
    "MinDeliveryDays" integer NOT NULL,
    "MaxDeliveryDays" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsDefault" boolean NOT NULL,
    "MinOrderAmount" numeric,
    "MaxOrderAmount" numeric,
    "MaxWeight" numeric,
    "IsFreeAboveAmount" boolean NOT NULL,
    "FreeShippingThreshold" numeric,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Shippings" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhoneNumber" character varying(15) NOT NULL,
    "FirstName" character varying(50),
    "LastName" character varying(50),
    "Email" character varying(256),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "WalletReconciliationAudits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WalletId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "SnapshotBalance" numeric NOT NULL,
    "LedgerBalance" numeric NOT NULL,
    "Delta" numeric NOT NULL,
    "DetectedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WalletReconciliationAudits" PRIMARY KEY ("Id")
);

CREATE TABLE "Wallets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CurrentBalance" numeric(18,2) NOT NULL,
    "ReservedBalance" numeric(18,2) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_Wallets" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Wallet_CurrentBalance_NonNegative" CHECK ("CurrentBalance" >= 0),
    CONSTRAINT "CK_Wallet_ReservedBalance_NonNegative" CHECK ("ReservedBalance" >= 0)
);

CREATE TABLE "Warehouses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "City" character varying(100) NOT NULL,
    "Address" character varying(500),
    "Phone" character varying(20),
    "IsActive" boolean NOT NULL,
    "IsDefault" boolean NOT NULL,
    "Priority" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id")
);

CREATE TABLE "AttributeValues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AttributeTypeId" integer NOT NULL,
    "Value" character varying(100) NOT NULL,
    "DisplayValue" character varying(100) NOT NULL,
    "HexCode" character varying(50),
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_AttributeValues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttributeValues_AttributeTypes_AttributeTypeId" FOREIGN KEY ("AttributeTypeId") REFERENCES "AttributeTypes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Brands" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Description" character varying(500),
    "CategoryId" integer NOT NULL,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Brands" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Brands_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "DiscountRestriction" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DiscountCodeId" integer NOT NULL,
    "Type" character varying(50) NOT NULL,
    "EntityId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_DiscountRestriction" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DiscountRestriction_DiscountCodes_DiscountCodeId" FOREIGN KEY ("DiscountCodeId") REFERENCES "DiscountCodes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Carts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "GuestToken" character varying(256),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LastUpdated" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "Type" character varying(100) NOT NULL,
    "IsRead" boolean NOT NULL,
    "ActionUrl" character varying(500),
    "RelatedEntityId" integer,
    "RelatedEntityType" character varying(100),
    "ReadAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "UserAddressId" integer,
    "ReceiverName" character varying(100) NOT NULL,
    "AddressSnapshot" jsonb NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "TotalProfit" numeric(18,2) NOT NULL,
    "ShippingCost" numeric(18,2) NOT NULL,
    "DiscountAmount" numeric(18,2) NOT NULL,
    "FinalAmount" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ShippingId" integer NOT NULL,
    "DiscountCodeId" integer,
    "PaymentDate" timestamp with time zone,
    "ShippedDate" timestamp with time zone,
    "DeliveryDate" timestamp with time zone,
    "IdempotencyKey" character varying(256) NOT NULL,
    "OrderNumber" character varying(50) NOT NULL,
    "CancellationReason" character varying(500),
    "CancelledBy" integer,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OrderStatusId" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_OrderStatus_OrderStatusId" FOREIGN KEY ("OrderStatusId") REFERENCES "OrderStatus" ("Id"),
    CONSTRAINT "FK_Orders_Shippings_ShippingId" FOREIGN KEY ("ShippingId") REFERENCES "Shippings" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tickets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Subject" character varying(200) NOT NULL,
    "Priority" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tickets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserAddresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "ReceiverName" character varying(100) NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "Province" character varying(50) NOT NULL,
    "City" character varying(50) NOT NULL,
    "Address" character varying(500) NOT NULL,
    "PostalCode" character varying(20) NOT NULL,
    "Latitude" numeric(10,7),
    "Longitude" numeric(10,7),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_UserAddresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserAddresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserOtps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "OtpHash" character varying(256) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_UserOtps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserOtps_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TokenSelector" character varying(256) NOT NULL,
    "TokenVerifierHash" character varying(256) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "CreatedByIp" character varying(45) NOT NULL,
    "UserAgent" character varying(500),
    "ReplacedByTokenHash" character varying(256),
    "SessionType" character varying(50) NOT NULL,
    "LastActivityAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_UserSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WalletLedgerEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WalletId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "AmountDelta" numeric(18,2) NOT NULL,
    "BalanceAfter" numeric(18,2) NOT NULL,
    "TransactionType" character varying(50) NOT NULL,
    "ReferenceType" character varying(50) NOT NULL,
    "ReferenceId" integer NOT NULL,
    "IdempotencyKey" character varying(200) NOT NULL,
    "CorrelationId" character varying(200),
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_WalletLedgerEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WalletLedgerEntries_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WalletReservations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WalletId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "OrderId" integer NOT NULL,
    "Status" character varying(20) NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_WalletReservations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WalletReservations_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "CategoryId" integer NOT NULL,
    "BrandId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "Stats_MinPrice" numeric(18,2) NOT NULL,
    "Stats_MaxPrice" numeric(18,2) NOT NULL,
    "Stats_TotalStock" integer NOT NULL,
    "Stats_AverageRating" numeric(3,2) NOT NULL,
    "Stats_ReviewCount" integer NOT NULL,
    "Stats_SalesCount" integer NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Brands_BrandId" FOREIGN KEY ("BrandId") REFERENCES "Brands" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DiscountUsage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "DiscountCodeId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "DiscountAmount" numeric(18,2) NOT NULL,
    "UsedAt" timestamp with time zone NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "IsCancelled" boolean NOT NULL,
    "CancelledAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_DiscountUsage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DiscountUsage_DiscountCodes_DiscountCodeId" FOREIGN KEY ("DiscountCodeId") REFERENCES "DiscountCodes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DiscountUsage_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DiscountUsage_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PaymentTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Authority" character varying(100) NOT NULL,
    "Gateway" character varying(50) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CardPan" character varying(20),
    "CardHash" character varying(100),
    "IpAddress" character varying(45),
    "ErrorMessage" character varying(500),
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentTransactions_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TicketMessage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TicketId" integer NOT NULL,
    "SenderId" integer,
    "Message" character varying(5000) NOT NULL,
    "IsAdminResponse" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_TicketMessage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TicketMessage_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Medias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FilePath" character varying(1000) NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FileType" character varying(100) NOT NULL,
    "FileSize" bigint NOT NULL,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" integer NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsPrimary" boolean NOT NULL,
    "AltText" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "IsActive" boolean NOT NULL,
    "BrandId" integer,
    "CategoryId" integer,
    "ProductId" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Medias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Medias_Brands_BrandId" FOREIGN KEY ("BrandId") REFERENCES "Brands" ("Id"),
    CONSTRAINT "FK_Medias_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id"),
    CONSTRAINT "FK_Medias_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id")
);

CREATE TABLE "ProductReviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OrderId" integer,
    "Rating" integer NOT NULL,
    "Title" character varying(100),
    "Comment" character varying(1000),
    "Status" character varying(50) NOT NULL,
    "IsVerifiedPurchase" boolean NOT NULL,
    "LikeCount" integer NOT NULL,
    "DislikeCount" integer NOT NULL,
    "AdminReply" character varying(1000),
    "RepliedAt" timestamp with time zone,
    "RejectionReason" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_ProductReviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductReviews_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductReviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProductVariants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "Sku" character varying(100) NOT NULL,
    "PurchasePrice" numeric(18,2) NOT NULL,
    "SellingPrice" numeric(18,2) NOT NULL,
    "OriginalPrice" numeric(18,2) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "ReservedQuantity" integer NOT NULL,
    "IsUnlimited" boolean NOT NULL,
    "LowStockThreshold" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "ShippingMultiplier" numeric(18,2) NOT NULL DEFAULT 1.0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Wishlists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Wishlists" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Wishlists_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Wishlists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CartItem" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CartId" integer NOT NULL,
    "VariantId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "SellingPrice" numeric NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_CartItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartItem_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItem_ProductVariants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "ProductVariants" ("Id")
);

CREATE TABLE "OrderItem" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "VariantId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductName" character varying(200) NOT NULL,
    "VariantSku" character varying(100),
    "VariantAttributes" text,
    "Quantity" integer NOT NULL,
    "PurchasePriceAtOrder" numeric(18,2) NOT NULL,
    "SellingPriceAtOrder" numeric(18,2) NOT NULL,
    "OriginalPriceAtOrder" numeric(18,2) NOT NULL,
    "DiscountAtOrder" numeric(18,2) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Profit" numeric(18,2) NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_OrderItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItem_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItem_ProductVariants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "ProductVariants" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProductVariantAttribute" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VariantId" integer NOT NULL,
    "AttributeValueId" integer NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_ProductVariantAttribute" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductVariantAttribute_AttributeValues_AttributeValueId" FOREIGN KEY ("AttributeValueId") REFERENCES "AttributeValues" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProductVariantAttribute_ProductVariants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductVariantShipping" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductVariantId" integer NOT NULL,
    "ShippingId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_ProductVariantShipping" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductVariantShipping_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductVariantShipping_Shippings_ShippingId" FOREIGN KEY ("ShippingId") REFERENCES "Shippings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StockLedgerEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VariantId" integer NOT NULL,
    "WarehouseId" integer,
    "OrderItemId" integer,
    "UserId" integer,
    "EventType" character varying(50) NOT NULL,
    "QuantityDelta" integer NOT NULL,
    "BalanceAfter" integer NOT NULL,
    "UnitCost" numeric NOT NULL,
    "ReferenceNumber" character varying(100),
    "CorrelationId" character varying(200),
    "Note" character varying(500),
    "Source" character varying(100),
    "IdempotencyKey" character varying(200) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_StockLedgerEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockLedgerEntries_ProductVariants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "ProductVariants" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StockLedgerEntries_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE SET NULL
);

CREATE TABLE "WarehouseStock" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseId" integer NOT NULL,
    "VariantId" integer NOT NULL,
    "OnHand" integer NOT NULL,
    "Reserved" integer NOT NULL,
    "Damaged" integer NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_WarehouseStock" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WarehouseStock_ProductVariants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WarehouseStock_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InventoryTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VariantId" integer NOT NULL,
    "TransactionType" character varying(50) NOT NULL,
    "UserId" integer,
    "Notes" character varying(500),
    "ReferenceNumber" character varying(100),
    "CorrelationId" character varying(200),
    "CartId" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OrderItemId1" integer,
    "_reversedByTransactionId" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryTransactions_InventoryTransactions__reversedByTran~" FOREIGN KEY ("_reversedByTransactionId") REFERENCES "InventoryTransactions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InventoryTransactions_OrderItem_OrderItemId1" FOREIGN KEY ("OrderItemId1") REFERENCES "OrderItem" ("Id"),
    CONSTRAINT "FK_InventoryTransactions_ProductVariants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "ProductVariants" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InventoryTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_AttributeValues_AttributeTypeId" ON "AttributeValues" ("AttributeTypeId");

CREATE INDEX "IX_AuditLogs_EventType" ON "AuditLogs" ("EventType");

CREATE INDEX "IX_AuditLogs_IsArchived" ON "AuditLogs" ("IsArchived");

CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");

CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");

CREATE INDEX "IX_AuditLogs_UserId_Timestamp" ON "AuditLogs" ("UserId", "Timestamp");

CREATE UNIQUE INDEX "IX_Brands_CategoryId_Name" ON "Brands" ("CategoryId", "Name");

CREATE UNIQUE INDEX "IX_Brands_Slug" ON "Brands" ("Slug");

CREATE UNIQUE INDEX "IX_CartItem_CartId_VariantId" ON "CartItem" ("CartId", "VariantId");

CREATE INDEX "IX_CartItem_VariantId" ON "CartItem" ("VariantId");

CREATE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");

CREATE UNIQUE INDEX "IX_Categories_Slug" ON "Categories" ("Slug");

CREATE UNIQUE INDEX "IX_DiscountCodes_Code" ON "DiscountCodes" ("Code");

CREATE UNIQUE INDEX "IX_DiscountRestriction_DiscountCodeId_Type_EntityId" ON "DiscountRestriction" ("DiscountCodeId", "Type", "EntityId");

CREATE UNIQUE INDEX "IX_DiscountUsage_DiscountCodeId_OrderId" ON "DiscountUsage" ("DiscountCodeId", "OrderId");

CREATE INDEX "IX_DiscountUsage_DiscountCodeId_UserId" ON "DiscountUsage" ("DiscountCodeId", "UserId");

CREATE INDEX "IX_DiscountUsage_OrderId" ON "DiscountUsage" ("OrderId");

CREATE INDEX "IX_DiscountUsage_UserId" ON "DiscountUsage" ("UserId");

CREATE INDEX "IX_InventoryTransactions__reversedByTransactionId" ON "InventoryTransactions" ("_reversedByTransactionId");

CREATE INDEX "IX_InventoryTransactions_OrderItemId1" ON "InventoryTransactions" ("OrderItemId1");

CREATE INDEX "IX_InventoryTransactions_UserId" ON "InventoryTransactions" ("UserId");

CREATE UNIQUE INDEX "IX_InventoryTransactions_VariantId_TransactionType_Correlation~" ON "InventoryTransactions" ("VariantId", "TransactionType", "CorrelationId") WHERE "CorrelationId" IS NOT NULL;

CREATE INDEX "IX_Medias_BrandId" ON "Medias" ("BrandId");

CREATE INDEX "IX_Medias_CategoryId" ON "Medias" ("CategoryId");

CREATE INDEX "IX_Medias_EntityType_EntityId" ON "Medias" ("EntityType", "EntityId");

CREATE INDEX "IX_Medias_ProductId" ON "Medias" ("ProductId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_OrderItem_OrderId" ON "OrderItem" ("OrderId");

CREATE INDEX "IX_OrderItem_VariantId" ON "OrderItem" ("VariantId");

CREATE UNIQUE INDEX "IX_Orders_IdempotencyKey" ON "Orders" ("IdempotencyKey");

CREATE UNIQUE INDEX "IX_Orders_OrderNumber" ON "Orders" ("OrderNumber");

CREATE INDEX "IX_Orders_OrderStatusId" ON "Orders" ("OrderStatusId");

CREATE INDEX "IX_Orders_ShippingId" ON "Orders" ("ShippingId");

CREATE INDEX "IX_Orders_Status" ON "Orders" ("Status");

CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");

CREATE UNIQUE INDEX "IX_OrderStatus_Name" ON "OrderStatus" ("Name") WHERE "IsDeleted" = false;

CREATE INDEX "IX_OutboxMessages_ProcessedAt" ON "OutboxMessages" ("ProcessedAt");

CREATE UNIQUE INDEX "IX_PaymentTransactions_Authority" ON "PaymentTransactions" ("Authority") WHERE "IsDeleted" = false;

CREATE INDEX "IX_PaymentTransactions_OrderId" ON "PaymentTransactions" ("OrderId");

CREATE INDEX "IX_ProductReviews_ProductId" ON "ProductReviews" ("ProductId");

CREATE INDEX "IX_ProductReviews_UserId" ON "ProductReviews" ("UserId");

CREATE INDEX "IX_Products_BrandId" ON "Products" ("BrandId");

CREATE INDEX "IX_ProductVariantAttribute_AttributeValueId" ON "ProductVariantAttribute" ("AttributeValueId");

CREATE UNIQUE INDEX "IX_ProductVariantAttribute_VariantId_AttributeValueId" ON "ProductVariantAttribute" ("VariantId", "AttributeValueId");

CREATE UNIQUE INDEX "IX_ProductVariants_ProductId_Sku" ON "ProductVariants" ("ProductId", "Sku") WHERE "IsDeleted" = false;

CREATE UNIQUE INDEX "IX_ProductVariantShipping_ProductVariantId_ShippingId" ON "ProductVariantShipping" ("ProductVariantId", "ShippingId");

CREATE INDEX "IX_ProductVariantShipping_ShippingId" ON "ProductVariantShipping" ("ShippingId");

CREATE UNIQUE INDEX "IX_StockLedgerEntries_IdempotencyKey" ON "StockLedgerEntries" ("IdempotencyKey");

CREATE INDEX "IX_StockLedgerEntries_VariantId" ON "StockLedgerEntries" ("VariantId");

CREATE INDEX "IX_StockLedgerEntries_WarehouseId" ON "StockLedgerEntries" ("WarehouseId");

CREATE INDEX "IX_TicketMessage_TicketId" ON "TicketMessage" ("TicketId");

CREATE INDEX "IX_Tickets_UserId" ON "Tickets" ("UserId");

CREATE INDEX "IX_UserAddresses_UserId" ON "UserAddresses" ("UserId");

CREATE INDEX "IX_UserOtps_UserId" ON "UserOtps" ("UserId");

CREATE UNIQUE INDEX "IX_Users_PhoneNumber" ON "Users" ("PhoneNumber");

CREATE UNIQUE INDEX "IX_UserSessions_TokenSelector" ON "UserSessions" ("TokenSelector");

CREATE INDEX "IX_UserSessions_UserId" ON "UserSessions" ("UserId");

CREATE UNIQUE INDEX "IX_WalletLedgerEntries_IdempotencyKey" ON "WalletLedgerEntries" ("IdempotencyKey");

CREATE INDEX "IX_WalletLedgerEntries_ReferenceType_ReferenceId" ON "WalletLedgerEntries" ("ReferenceType", "ReferenceId");

CREATE INDEX "IX_WalletLedgerEntries_UserId_CreatedAt" ON "WalletLedgerEntries" ("UserId", "CreatedAt");

CREATE INDEX "IX_WalletLedgerEntries_WalletId" ON "WalletLedgerEntries" ("WalletId");

CREATE INDEX "IX_WalletReservations_OrderId" ON "WalletReservations" ("OrderId");

CREATE INDEX "IX_WalletReservations_Status_ExpiresAt" ON "WalletReservations" ("Status", "ExpiresAt");

CREATE INDEX "IX_WalletReservations_WalletId_Status" ON "WalletReservations" ("WalletId", "Status");

CREATE UNIQUE INDEX "IX_Wallets_UserId" ON "Wallets" ("UserId");

CREATE UNIQUE INDEX "IX_Warehouses_Code" ON "Warehouses" ("Code") WHERE "IsDeleted" = false;

CREATE INDEX "IX_WarehouseStock_VariantId" ON "WarehouseStock" ("VariantId");

CREATE UNIQUE INDEX "IX_WarehouseStock_WarehouseId_VariantId" ON "WarehouseStock" ("WarehouseId", "VariantId");

CREATE INDEX "IX_Wishlists_ProductId" ON "Wishlists" ("ProductId");

CREATE UNIQUE INDEX "IX_Wishlists_UserId_ProductId" ON "Wishlists" ("UserId", "ProductId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225184425_1', '10.0.3');

COMMIT;

