global using System.Globalization;
global using System.Net;
global using System.Text;
global using System.Text.Json;
global using Amazon.S3;
global using Amazon.S3.Model;
global using Bogus;
global using DotNet.Testcontainers.Builders;
global using MapsterMapper;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Microsoft.FeatureManagement;
global using Npgsql;
global using NSubstitute;
global using NSubstitute.ExceptionExtensions;
global using Respawn;
global using Shouldly;
global using Tests.TestInfrastructure.Database;
global using FilePath = SharedKernel.ValueObjects.FilePath;
global using ValidationResult = FluentValidation.Results.ValidationResult;
