global using DataAccessLayer.Models.Base;
global using DataAccessLayer.Models.Order;
global using DataAccessLayer.Models.Product;
global using DataAccessLayer.Models.Auth;
global using DataAccessLayer.Models.User;
global using DataAccessLayer.Models.Cart;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;