// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(MechanicContext))]
    partial class MechanicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Order.TOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalProfit")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TOrders");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product.TProductTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TProductTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product.TProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int?>("SellingPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("TProducts");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User.TUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TUsers");
                });

            modelBuilder.Entity("TOrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Profit")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PurchasePrice")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SellingPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserOrderId")
                        .IsUnique()
                        .HasFilter("[UserOrderId] IS NOT NULL");

                    b.ToTable("TOrderDetails");
                });

            modelBuilder.Entity("TOrderDetailsTProducts", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("TOrderDetailsTProducts");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Order.TOrders", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User.TUsers", "User")
                        .WithMany("UserOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product.TProducts", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Product.TProductTypes", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("TOrderDetails", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Order.TOrders", "UserOrder")
                        .WithOne("OrderDetail")
                        .HasForeignKey("TOrderDetails", "UserOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserOrder");
                });

            modelBuilder.Entity("TOrderDetailsTProducts", b =>
                {
                    b.HasOne("TOrderDetails", null)
                        .WithMany()
                        .HasForeignKey("OrderDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Product.TProducts", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Order.TOrders", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product.TProductTypes", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User.TUsers", b =>
                {
                    b.Navigation("UserOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
